language: node_js
node_js:
- '0.10'
sudo: false
notifications:
  irc: irc.freenode.org#socket.io
matrix:
  include:
  - node_js: '0.10'
    env: BROWSER_NAME=chrome BROWSER_VERSION=latest
  - node_js: '0.10'
    env: BROWSER_NAME=safari BROWSER_VERSION=latest
  - node_js: '0.10'
    env: BROWSER_NAME=ie BROWSER_VERSION=6
  - node_js: '0.10'
    env: BROWSER_NAME=ie BROWSER_VERSION=7
  - node_js: '0.10'
    env: BROWSER_NAME=ie BROWSER_VERSION=8
  - node_js: '0.10'
    env: BROWSER_NAME=ie BROWSER_VERSION=9
  - node_js: '0.10'
    env: BROWSER_NAME=ie BROWSER_VERSION=10 BROWSER_PLATFORM="Windows 2012"
  - node_js: '0.10'
    env: BROWSER_NAME=ie BROWSER_VERSION=latest BROWSER_PLATFORM="Windows 2012"
  - node_js: '0.10'
    env: BROWSER_NAME=iphone BROWSER_VERSION=6.1
  - node_js: '0.10'
    env: BROWSER_NAME=iphone BROWSER_VERSION=7.1
  - node_js: '0.10'
    env: BROWSER_NAME=android BROWSER_VERSION=4.0
  - node_js: '0.10'
    env: BROWSER_NAME=android BROWSER_VERSION=4.1
  - node_js: '0.10'
    env: BROWSER_NAME=android BROWSER_VERSION=4.2
  - node_js: '0.10'
    env: BROWSER_NAME=android BROWSER_VERSION=4.3
  - node_js: '0.10'
    env: BROWSER_NAME=android BROWSER_VERSION=4.4
env:
  global:
  - secure: ZLB2xNwK+Bv+aYn2Nxc8Y7RhWZbgvV7swM57c8Z4HarjZmZ2xqmJIcPEfbGL9qW9EObnxzyAF5mFSVoA2LgFyaolzPCd0/aSN8RCvyyLe3ZXOgAHtMihxX9DZyUp7CUhHUd557W37EQF2YPvAyP6sjDAZOq6BC643Qt7k/BltcA=
  - secure: AjUYW6swrtbB+XOZo3vizxIpoyjY7k2MF6XCvZoO+cCp+kb0bvZwlJEurxvGsW29wNM2qcLTHZO+6kwHBVHSLphQYrSScEGOKqmtpB1zzrpmKA/5cugH4Tyrx4uTwh8IR5TWqEeHoWaXq1448TDXCCDjzsRWOWEltRxDeTR8h8Y=
